app/config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

app/src/Model/Entity/Artist.php
<?php
// src/Model/Entity/Movie.php
namespace App\Model\Entity;

use Cake\ORM\Entity;

class Artist extends Entity{


    protected $_accessible = [
        '*' => true,
        'id' => false
    ];
}

app/src/Model/Table/ArtistsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Table;
use Cake\Validation\Validator;

class ArtistsTable extends Table{

    public function initialize(array $config) {
        $this->addBehavior('Timestamp');


        $this->hasMany('Albums',[
            'foreingKey' => 'artist_id',
        ]);
        $this->hasMany('Bookmarks',[
            'foreingKey' => 'artist_id',
        ]);

    }

    public function validationDefault(Validator $v){
        $v->notEmpty('psodonym')
            ->allowEmpty('debut')
            ->allowEmpty('country')
            ->maxLength('country', 100)
            ->allowEmpty('spotify')
            ->maxLength('spotify', 300)
            ->allowEmpty('picture')
            ->maxLength('picture', 100);
        return $v;
    }

}

app/src/Model/Table/RequestsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Table;
use Cake\Validation\Validator;

class RequestsTable extends Table{

    public function initialize(array $config) {
        $this->addBehavior('Timestamp');

        $this->belongsTo('users',[
            'foreingKey' => 'user_id',
            'joinType' => 'INNER'
        ]);


    }

    public function validationDefault(Validator $v){
        $v->notEmpty('artistname')
            ->maxLength('artistname', 100)
            ->notEmpty('albumtitle')
            ->maxLength('spotify', 100);
        return $v;
    }

}

app/src/Controller/ArtistsController.php
<?php

namespace App\Controller;

use App\Model\Entity\Comments;
use Cake\Http\Exception\NotFoundException;

class ArtistsController extends AppController {

    // cett fonction permet d'afficher les artistes trié par ordre alphabetique
     public function index(){
    	$artists = $this->Artists->find()->order('psodonym');
        $this->set(compact('artists'));
     }

     // Cette fonction permet d'afficher un artistes avec les commentaires qui vont avec.
     public function view($id){
         	$one = $this->Artists->get($id, [
                'contain' => ['Albums', 'Bookmarks.Users']

            ]);
         	$this->set(['one'=>$one]);
     }

     // cette fonction permet de pouvoir changer la photo de profile d'un artiste
     // todo mettre le check admin
     public function editpicture($id){
             $artists = $this->Artists->get($id);
             $oldFile = $artists->picture;

             if($this->request->is(['post', 'put'])){
                 $this->Artists->patchEntity($artists, $this->request->getData());

                 if(!empty($this->request->getData()['picture']['name'])
                 && in_array($this->request->getData()['picture']['type'], ['image/png', 'image/jpg', 'image/jpeg', 'image/gif'])){
                     $ext = pathinfo($this->request->getData()['picture']['name'], PATHINFO_EXTENSION);
                     $name = 'a-'.rand(0,3000).'-'.time().'.'.$ext;
                     $address = WWW_ROOT.'/data/artistes/'.$name;
                     $artists->picture = $name;
                     move_uploaded_file($this->request->getData('picture')['tmp_name'],$address);

                     if($this->Artists->save($artists)){

                         if(!empty($oldFile) && file_exists(WWW_ROOT . '/data/artistes/' . $oldFile))
                             unlink(WWW_ROOT . '/data/artistes/' . $oldFile);

                         $this->Flash->success('cette modif est faite');
                         return $this->redirect(['action' => 'view', $artists->id]);
                     }
                 }else{
                     $artists->picture= $oldFile;
                     $this->Flash->error("ce format de donnée est pas bon frère");
                 }
             }
             $this->set(compact('artists'));
     }

     // Cette fonction permet de pouvoir editer un artiste sauf l'image
     // todo voir pour mettre la fonction de changement d'image dedans.
     public function edit($id){
             $artists = $this->Artists->get($id);

             if($this->request->is(['post', 'put'])){
                 $this->Artists->patchEntity($artists, $this->request->getData());

     			if($this->Artists->save($artists)){
     				$this->Flash->success('Modif ok');
     				return $this->redirect(['action' => 'view', $artists->id]);
     			}
                  $this->Flash->error('la modif a planté tu peux essayer encore');
             }
             $this->set(compact('artists'));
     }

     // Cette focntion permet d'ajouter un artiste
    public function add() {
            $new = $this->Artists->newEntity();
            if($this->request->is('post')){
                $new = $this->Artists->patchEntity($new, $this->request->getData());

                if(in_array($this->request->getData()['picture']['type'], array('image/png','image/jpg', 'image/jpeg', 'image/gif'))){
                    $ext = pathinfo($this->request->getData('picture')['name'], PATHINFO_EXTENSION);
                    $name = 'a-'.rand(0,3000).'-'.time().'.'.$ext;
                    $adress=WWW_ROOT.'/data/artistes/'.$name;
                    $new->picture = $name;
                    move_uploaded_file($this->request->getData('picture')['tmp_name'],$adress);
                }else {
                    $new->picture = null;
                    $this->Flash->error('tu peux encore essayer');
                }
                if ($this->Artists->save($new)){
                    $this->Flash->success('jour de fête tu as reussi');
                    return $this->redirect(['action' => 'index']);
                }
                $this->Flash->error('si tu vois ce message, c\' que tu es mauvais');
            }
            $this->set(compact('new'));
        }
}

app/src/Template/Artists/add.ctp
<?php //file src/Templates/Movies/add.ctp ?>

<?= $this->Form->create($new, ['enctype' => 'multipart/form-data']) ?>
    <h1>Ajouter un artiste</h1>
<?= $this->Form->control('psodonym', ['label' => 'nom de l\'artiste']) ?>
<?= $this->Form->control('debut', ['label' => 'debut']) ?>
<?= $this->Form->control('country', ['label' => 'pays d\'origin']) ?>
<?= $this->Form->control('spotify', ['label' => 'nom spotify']) ?>

<?=  $this->Form->control('picture', ['type' => 'file', 'label' => 'Affiche']) ?>

<?= $this->Form->button('Ajouter') ?>
<?= $this->Form->end() ?>

app/src/Template/Artists/edit.ctp
<?php //file src/Templates/Movies/edit.ctp ?>

<?= $this->Form->create($artists) ?>
    <h1>Modifier un film</h1>
<?= $this->Form->control('psodonym', ['label' => 'Nom de l\'artiste']) ?>
<?= $this->Form->control('country', ['label' => 'Pays d\'oirigin']) ?>
<?= $this->Form->control('debut', ['label' => 'début']) ?>

<?= $this->Form->button('Modifier') ?>
<?= $this->Form->end() ?>

app/src/Template/Artists/editpicture.ctp
<?php
?>
<?= $this->Form->create($artists, ['enctype' => 'multipart/form-data']) ?>
    <h1>Modification de l'affiche de : <?= $artists->title ?></h1>

<?=  $this->Form->control('picture', ['type' => 'file', 'label' => 'Affiche']) ?>
    <figure>
        <?php //si on a l'image, on l'affiche; sinon, on met une image par defaut
        if (!empty($artists->picture)) { ?>
            <?= $this->Html->image( '../data/artistes/'.$artists->picture, ['alt' => 'Affiche de : '.$artists->title ] ) ?>
        <?php }else { ?>
            <?= $this->Html->image('defaut.jpg', ['alt' => 'Visuel non disponible' ] ) ?>
        <?php } ?>
        <figcaption>
            Image actuelle
        </figcaption>
    </figure>

<?= $this->Form->button('Modifier') ?>
<?= $this->Form->end() ?>

app/src/Template/Artists/index.ctp
<h1>Liste des Artistes</h1>

<p>Il y a <?= $artists->count() ?> Artiste<?= ($artists->count()>1) ? 's' : '' ?></p>

<table>
    <thead>
    <tr>
        <th>Artiste</th>
        <th>Pays</th>
        <th>Lien spotify</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($artists as $one) : ?>
        <tr>
            <td><?= $this->Html->link($one->psodonym, ['action'=>'view', $one->id]) ?></td>
            <td><?= $one->country ?></td>
            <td><?= $one->spotify?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

app/src/Template/Artists/view.ctp
<?php //file src/Tempaltes/Movies/view.ctp
//var_dump($one);
//echo $one;

$b = 0;
?>


<h1><?= $one->psodonym?></h1>
<figure>
    <?php //si on a l'image, on l'affiche; sinon, on met une image par defaut
    if (empty($one->poster)) { ?>
        <?= $this->Html->image( '../data/artistes/'.$one->picture, ['alt' => 'Affiche de : '.$one->psodonym ] ) ?>
    <?php }else { ?>
        <?= $this->Html->image('defaut.jpg', ['alt' => 'Visuel non disponible' ] ) ?>
    <?php } ?>
    <figcaption>
        <?= $this->Html->link('Modifier la photo de profile', ['action' => 'editpicture', $one->id], ['class' => "button"]) ?>
    </figcaption>
</figure>
    <iframe src="https://open.spotify.com/follow/1/?uri=spotify:artist:<?php echo ($one->spotify); ?>&size=detail&theme=light" width="300" height="56" scrolling="no" frameborder="0" style="border:none; overflow:hidden;" allowtransparency="true"></iframe>


<p>
    <span class="label">Année de commencement :</span>
    <?= $one->debut ?>
</p>
<p>
    <span class="label">Pays d'origin :</span>
    <?= $one->country ?>
</p>
<p>
    <?= $this->Html->link('Modifier', ['action' => 'edit', $one->id], ['class' => "button"]) ?>
</p>

<h2>Albums</h2>
    <?php foreach ($one->albums as $key => $value){ ?>
        <p class="infos"> <?= $value->created->i18nFormat('dd/mm/yyyy HH:MM:SS')?> : <?= $this->Html->link($value->title, ['controller' => 'Albums', 'action'=>'viewAlbum', $value->id]) ?>. <?= $value->cover?></p>
    <?php }; ?>

<h2>Favorie</h2>


<?= $this->Html->link('Modifier', ['action' => 'add', $one->id], ['class' => "button"]) ?>


<?php
if (!empty($one->bookmarks)){
    //var_dump($one);
    foreach ($one->bookmarks as $key ){
        ?>
        <p class="infos"><?= $key->user->pseudo ?></p>
        <?php
        $b = $b + 1;
    };
    $result = $b;
    echo $result . ' Personnes aime cet artists';
}else{
    echo 'Personne n aime ce truc';
}
?>